# -*- coding: utf-8 -*-
"""Linear Regression Single Variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iCIoDB4c-hceBupu3i-iq5oQStGYdhG0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv("/content/drive/MyDrive/homes - Sheet1.csv")
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('Area m2')
plt.ylabel('Price IRT')
plt.scatter(df.area, df.prices, color='green', marker='+')

new_df = df.drop('prices',axis='columns')
new_df

prices = df.prices
prices

reg = linear_model.LinearRegression()
reg.fit(new_df,prices)

reg.predict([[100]])

reg.coef_

reg.intercept_

100 * 8000000. + 2.384185791015625e-07

reg.predict([[2000]])